url: http://hillaryprison.org
baseurl: http://presente.github.io/hillary/

# Site settings
title: HillaryPrison.org
email: info@presente.org
description: "Hillary / DNC: Cut ties with private prisons!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
